/**
 * Generated by Orant Lang Compiler
 * Do not edit this file directly
 */

import { OrantRuntime, Entity, Sequence, Renderer } from './lang/stdlib.js';

const runtime = new OrantRuntime();

// Invoke TestAngel as Angel
const TestAngel = new Entity('TestAngel', 'Angel', {
  color: '#F8F9FA',
  wings: 6,
  flywheel: 'spinning',
});
runtime.addEntity(TestAngel);

// Sequence SimpleTest
const SimpleTest = new Sequence('SimpleTest', {
  duration: '1s',
  frames: [
    {
      frameNumber: 1,
      actions: [
        {
          type: 'appear',
          entity: 'TestAngel',
          params: {"position":{"name":"center"}}
        },
      ]
    },
    {
      frameNumber: 10,
      actions: [
        {
          type: 'glow',
          entity: 'TestAngel',
          params: {"intensity":"bright"}
        },
      ]
    },
    {
      frameNumber: 20,
      actions: [
        {
          type: 'float',
          entity: 'TestAngel',
          params: {"manner":"gentle"}
        },
      ]
    },
  ]
});
runtime.addSequence(SimpleTest);

// Render SimpleTest
const renderer_SimpleTest = new Renderer({
  sceneName: 'SimpleTest',
  sequence: SimpleTest,
});
runtime.render(renderer_SimpleTest);


// Start the Orant runtime
runtime.start();
