/**
 * Orant Lang Code Generator
 * Generates JavaScript code from AST
 */

export class CodeGenerator {
  constructor(ast) {
    this.ast = ast;
    this.entities = new Map();
    this.sequences = new Map();
    this.indentLevel = 0;
  }

  indent() {
    return '  '.repeat(this.indentLevel);
  }

  generate() {
    let code = this.generateHeader();
    code += this.generateBody();
    code += this.generateFooter();
    return code;
  }

  generateHeader() {
    return `/**
 * Generated by Orant Lang Compiler
 * Do not edit this file directly
 */

import { OrantRuntime, Entity, Sequence, Renderer } from './lang/stdlib.js';

const runtime = new OrantRuntime();

`;
  }

  generateBody() {
    let code = '';

    for (const statement of this.ast.statements) {
      code += this.generateStatement(statement);
      code += '\n';
    }

    return code;
  }

  generateFooter() {
    return `
// Start the Orant runtime
runtime.start();
`;
  }

  generateStatement(statement) {
    switch (statement.type) {
      case 'InvokeStatement':
        return this.generateInvokeStatement(statement);
      case 'SequenceStatement':
        return this.generateSequenceStatement(statement);
      case 'RenderStatement':
        return this.generateRenderStatement(statement);
      default:
        throw new Error(`Unknown statement type: ${statement.type}`);
    }
  }

  generateInvokeStatement(statement) {
    const { entityName, entityType, properties } = statement;

    this.entities.set(entityName, { type: entityType, properties });

    let code = `// Invoke ${entityName} as ${entityType}\n`;
    code += `const ${entityName} = new Entity('${entityName}', '${entityType}', {\n`;

    this.indentLevel++;
    for (const [key, value] of Object.entries(properties)) {
      code += `${this.indent()}${key}: ${this.generateValue(value)},\n`;
    }
    this.indentLevel--;

    code += `});\n`;
    code += `runtime.addEntity(${entityName});\n`;

    return code;
  }

  generateSequenceStatement(statement) {
    const { name, frames, properties } = statement;

    this.sequences.set(name, { frames, properties });

    let code = `// Sequence ${name}\n`;
    code += `const ${name} = new Sequence('${name}', {\n`;

    this.indentLevel++;

    // Generate properties
    for (const [key, value] of Object.entries(properties)) {
      code += `${this.indent()}${key}: ${this.generateValue(value)},\n`;
    }

    // Generate frames
    code += `${this.indent()}frames: [\n`;
    this.indentLevel++;

    for (const frame of frames) {
      code += this.generateFrameBlock(frame);
    }

    this.indentLevel--;
    code += `${this.indent()}]\n`;

    this.indentLevel--;
    code += `});\n`;
    code += `runtime.addSequence(${name});\n`;

    return code;
  }

  generateFrameBlock(frame) {
    const { frameNumber, actions } = frame;

    let code = `${this.indent()}{\n`;
    this.indentLevel++;

    code += `${this.indent()}frameNumber: ${frameNumber},\n`;
    code += `${this.indent()}actions: [\n`;

    this.indentLevel++;
    for (const action of actions) {
      code += this.generateAction(action);
    }
    this.indentLevel--;

    code += `${this.indent()}]\n`;

    this.indentLevel--;
    code += `${this.indent()}},\n`;

    return code;
  }

  generateAction(action) {
    const { actionType, entity, params } = action;

    let code = `${this.indent()}{\n`;
    this.indentLevel++;

    code += `${this.indent()}type: '${actionType}',\n`;
    code += `${this.indent()}entity: '${entity}',\n`;
    code += `${this.indent()}params: ${JSON.stringify(params)}\n`;

    this.indentLevel--;
    code += `${this.indent()}},\n`;

    return code;
  }

  generateRenderStatement(statement) {
    const { sceneName, properties } = statement;

    let code = `// Render ${sceneName}\n`;
    code += `const renderer_${sceneName} = new Renderer({\n`;

    this.indentLevel++;
    code += `${this.indent()}sceneName: '${sceneName}',\n`;

    if (this.sequences.has(sceneName)) {
      code += `${this.indent()}sequence: ${sceneName},\n`;
    }

    for (const [key, value] of Object.entries(properties)) {
      code += `${this.indent()}${key}: ${this.generateValue(value)},\n`;
    }

    this.indentLevel--;
    code += `});\n`;
    code += `runtime.render(renderer_${sceneName});\n`;

    return code;
  }

  generateValue(value) {
    if (typeof value === 'string') {
      // Check if it's a color
      if (value.startsWith('#')) {
        return `'${value}'`;
      }
      // Check if it's a reference to an entity
      if (this.entities.has(value)) {
        return value;
      }
      return `'${value}'`;
    } else if (typeof value === 'number') {
      return value;
    } else if (typeof value === 'object') {
      return JSON.stringify(value);
    }
    return `'${value}'`;
  }
}

// Helper function to generate code from AST
export function generate(ast) {
  const codegen = new CodeGenerator(ast);
  return codegen.generate();
}
